name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: 20
  CC: clang
  CXX: clang++

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build_type: [Release, Debug]
        os:
          - macos-15
          - macos-15-intel
          - ubuntu-22.04
          - ubuntu-22.04-arm
        include:
          - os: macos-15
            platform: darwin
            arch: arm64
          - os: macos-15-intel
            platform: darwin
            arch: x64
          - os: ubuntu-22.04
            platform: linux
            arch: x64
          - os: ubuntu-22.04-arm
            platform: linux
            arch: arm64

    name: ${{ matrix.platform }}-${{ matrix.arch }}-${{ matrix.build_type }}
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: ./.github/actions/build-native
        with:
          build_type: ${{ matrix.build_type }}
          upload_artifact: ${{ matrix.build_type == 'Release' && 'true' || 'false' }}
          artifact_retention_days: '14'
          platform: ${{ matrix.platform }}
          arch: ${{ matrix.arch }}

  sanitize:
    runs-on: ubuntu-22.04
    name: ASAN+UBSan test
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build zlib1g-dev libboost-dev clang python3-pip
          pip3 install --user 'cmake>=3.24'
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Test with ASan and UBSan
        run: |
          npm ci --ignore-scripts
          make sanitize

  coverage:
    runs-on: ubuntu-22.04
    name: Coverage
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build zlib1g-dev libboost-dev clang llvm python3-pip
          pip3 install --user 'cmake>=3.24'
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Coverage report
        run: |
          npm ci --ignore-scripts
          make coverage
